### ISSUE TITLE
new to generic-device-plugin, having trouble mounting TPM into pod

### ISSUE THREAD

**Issue by wahahawasabi** [squat/generic-device-plugin#79]
Hi, I have been trying to figure out how to mount `/dev/tpmrm0` into the kubernetes pod when i came across this project.

I'm running kubernetes on docker-desktop, and based on the instructions in the readme file, this is what i have done:

generic-device.yaml
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: generic-device-plugin
  namespace: kube-system
  labels:
    app.kubernetes.io/name: generic-device-plugin
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: generic-device-plugin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: generic-device-plugin
    spec:
      priorityClassName: system-node-critical
      tolerations:
        - operator: "Exists"
          effect: "NoExecute"
        - operator: "Exists"
          effect: "NoSchedule"
      containers:
        - image: squat/generic-device-plugin
          args:
            - --device
            - |
              name: tpmrm
              groups:
                - paths:
                    - path: /dev/tpmrm0
          name: generic-device-plugin
          resources:
            requests:
              cpu: 50m
              memory: 10Mi
            limits:
              cpu: 50m
              memory: 20Mi
          ports:
            - containerPort: 8080
              name: http
          securityContext:
            privileged: true
          volumeMounts:
            - name: device-plugin
              mountPath: /var/lib/kubelet/device-plugins
            - name: dev
              mountPath: /dev
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins
        - name: dev
          hostPath:
            path: /dev
  updateStrategy:
    type: RollingUpdate
```

pod.yaml
```
apiVersion: v1
kind: Pod
metadata:
  name: tpm-test
spec:
  containers:
    - name: tpm-container
      image: alpine:latest
      command: [ "sleep", "infinity" ]
      resources:
        limits:
          squat.ai/tpmrm: 1
```

The pod seems to be able to launch, but I am not able to see `/dev/tpmrm0` in the alpine container. Is there anything i am missing? Also, how do i know if i'm referencing `squat.ai/tpmrm` correctly

this is the output from `generic-device-plugin` daemon:
```
{"caller":"main.go:218","msg":"Starting the generic-device-plugin for \"squat.ai/tpmrm\".","ts":"2025-05-09T18:59:54.24862209Z"}
{"caller":"plugin.go:114","level":"info","msg":"listening on Unix socket","resource":"squat.ai/tpmrm","socket":"/var/lib/kubelet/device-plugins/gdp-c3F1YXQuYWkvdHBtcm0=-1746817194.sock","ts":"2025-05-09T18:59:54.248758355Z"}
{"caller":"plugin.go:122","level":"info","msg":"starting gRPC server","resource":"squat.ai/tpmrm","ts":"2025-05-09T18:59:54.248906343Z"}
{"caller":"plugin.go:176","level":"info","msg":"waiting for the gRPC server to be ready","resource":"squat.ai/tpmrm","ts":"2025-05-09T18:59:54.248938894Z"}
{"caller":"plugin.go:188","level":"info","msg":"the gRPC server is ready","resource":"squat.ai/tpmrm","ts":"2025-05-09T18:59:54.24933143Z"}
{"caller":"plugin.go:226","level":"info","msg":"registering plugin with kubelet","resource":"squat.ai/tpmrm","ts":"2025-05-09T18:59:54.249347149Z"}
{"caller":"generic.go:232","level":"info","msg":"starting listwatch","resource":"squat.ai/tpmrm","ts":"2025-05-09T18:59:54.250929707Z"}

```
